#!/bin/bash

#lein dependencies
lein deps

#postgres setup
dropdb foodapp
createdb foodapp
psql -d foodapp -c "create user foodapp with password 'foodapp';"
psql -d foodapp -c "alter database foodapp owner to foodapp;"
psql -U foodapp -d foodapp -f doc/schema.sql
